name: "Python Linter: mypy, autoflake, isort, black"
description: "Ensure Python code quality. Supports autoflake, black, mypy and isort."
branding:
  icon: "underline"
  color: "blue"
inputs:
  source:
    description: "Source file or directory"
    required: false
    default: "."
  strict:
    description: "Set strictness for lint [low, medium, high]"
    required: false
    default: "medium"
  mypy-options:
    description: "Mypy options"
    required: false
    default: ""
  pylint-options:
    description: "Pylint options"
    required: false
    default: ""
  black-options:
    description: "Autoflake options"
    required: false
    default: "--remove-all-unused-imports -i"
  isort-options:
    description: "Isort options"
    required: false
    default: "--profile black"

runs:
  using: "Docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source }}
    - ${{ inputs.strict }}
    - ${{ inputs.mypy-options }}
    - ${{ inputs.autoflake-options }}
    - ${{ inputs.black-options }}
    - ${{ inputs.isort-options }}