name: "Python Linter: autoflake, isort, black"
description: "Ensure Python code quality. Supports autoflake, isort and black"
branding:
  icon: "underline"
  color: "blue"
inputs:
  source:
    description: "Source file or directory"
    required: false
    default: "."
  strict:
    description: "Set strictness for lint [low, medium, high]"
    required: false
    default: "medium"
  autoflake-options:
    description: "Autoflake options"
    required: false
    default: "--remove-all-unused-imports -i"
  isort-options:
    description: "Isort options"
    required: false
    default: "--profile black"
  black-options:
    description: "Black options"
    required: false
    default: ""

runs:
  using: "Docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source }}
    - ${{ inputs.strict }}
    - ${{ inputs.autoflake-options }}
    - ${{ inputs.isort-options }}
    - ${{ inputs.black-options }}