name: "Python Linter: autoflake, isort, black"
description: "Ensure Python code quality. Supports autoflake, isort and black"
branding:
  icon: "underline"
  color: "blue"
inputs:
  source:
    description: "Source file or directory"
    required: false
    default: "."
  autoflake-options:
    description: "Autoflake options"
    required: false
    default: "--remove-all-unused-imports -r -c"
  isort-options:
    description: "Isort options"
    required: false
    default: "--profile black"
  black-options:
    description: "Black options"
    required: false
    default: "--diff --color --check"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install linting libraries
      run: pip install autoflake isort black
      shell: bash
    - name: Autoflake
      run: autoflake ${{ inputs.source }} ${{ inputs.autoflake-options }}
      shell: bash
    - name: Isort
      run: isort ${{ inputs.source }} ${{ inputs.isort-options }}
      shell: bash
    - name: Black
      run: black ${{ inputs.source }} ${{ inputs.black-options }}
      shell: bash